### ISSUE TITLE
(Not an issue as such) .NET 4.7.1 Framework reliance

### ISSUE THREAD

**Issue by bohdanszymanik** [CompositionalIT/houseprice-sales#17]
Had a confusing error message when running build.cmd about an IsUnion method not being found while doing the toJson conversion in Importdata.FableJson.toJson. Realised it was because I didn't have the full .net 4.7.1 framework on the workstation I was on - maybe a test or warning could be useful. After the framework install it ran fine.

**Comment by isaacabraham** [comment]
To be honest we  could downgrade to 452 which is much more common.

**Comment by isaacabraham** [comment]
I've now checked again - we need 471 for exactly that FableJson package. I've changed over to netstandard2.0 wherever possible which seems to work though. There's a now also a 461 in there for FSharp.Data, which isn't yet netstandard.
